apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: {{APP_IMAGE}}
        env:
        - name: DB_HOST
          value: "db"  # Matches the PostgreSQL service name
        - name: DB_USER
          value: "admin"  # Matches POSTGRES_USER
        - name: DB_PASSWORD
          value: "password"  # Matches POSTGRES_PASSWORD
        ports:
        - containerPort: 3000
