apiVersion: v1
kind: Service
metadata:
  name: mailcatcher-service
spec:
  selector:
    app: mailcatcher
  type: ClusterIP  # Internal-only service (not exposed externally)
  ports:
    - name: http
      protocol: TCP
      port: 1080
      targetPort: 1080
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
