apiVersion: v1
kind: Service
metadata:
  name: mailcatcher-service
spec:
  selector:
    app: mailcatcher
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 1080
    - protocol: TCP
      port: 1025
      targetPort: 1025
