apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: "admin"  # Ensure this matches the app config
        - name: POSTGRES_PASSWORD
          value: "password"  # Ensure this matches the app config
        ports:
        - containerPort: 5432
