apiVersion: v1
kind: Service
metadata:
  name: db  # Change the service name to 'db'
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None  # Headless service for internal DB communication
